### ISSUE TITLE
Rectangular templates not rounding

### ISSUE THREAD

**Issue by notrealdan** [cdverrett94/rounded-measured-templates#1]
Great module, and works well for most template types, but it seems to not work for rectangular ones.  Can you check on this?  Thanks!
![image](https://user-images.githubusercontent.com/28198633/97922689-17c3df80-1d1a-11eb-80e6-61c75dfbbb0d.png)

**Comment by cdverrett94** [comment]
Thanks. I don't know how I missed that in the testing. So the distance for the square template is the distance from the starting point to the end point, or the hypotenuse of the right angles. That distance is correctly being rounded, but obviously, that's not the desired result. I'll work on the solution later this evening and hopefully get that fixed. Thanks for the report!
