### ISSUE TITLE
[Feature Request] Snap to steps instead of multiples

### ISSUE THREAD

**Issue by mrkwnzl** [cdverrett94/rounded-measured-templates#3]
Hey! I was wondering if it would be possible to have the measured templates snap to steps instead of multiples of a single value. For example, some games use a distance band instead of measuring precisely, where the distances are something like Close Distance (3 m), Short Distance (15 m), Long Distance (30 m) and Very Long Distance (>30 m). While this can be replicated by giving a value of 3, of course, it would be awesome if I were able to just write something like “3, 15, 30” into the distance field in the settings.

For extra awesomeness, it would snap according to these steps, and beyond them according to the map setting (just as if the distance field is left blank) or any other specified value (so that it might be possible to have the bands snap to 3 m, 15 m, 30 m, and then in 1 m steps (or whatever other value is given).

Thanks for considering!

**Comment by cdverrett94** [comment]
It should definitely be possible, but I'll have to play around with it to see what I can come up with. Don't expect anything super quickly on this one.

**Comment by cdverrett94** [comment]
@mrkwnzl So managed to find some time and it turned out to be a lot easier than I expected to do. Let me know how that works for you and if it's what you were looking for!

**Comment by mrkwnzl** [comment]
Wow, awesome! It’s exactly what I imagined! Thank you so much! Works perfectly!

**Comment by cdverrett94** [comment]
Glad it's what you were looking for! 😀
