### ISSUE TITLE
Define angle rounding for rays and cones separately.

### ISSUE THREAD

**Issue by zeltordaeon** [cdverrett94/rounded-measured-templates#6]
For myself, I know I want to be able to snap cones in 45-degree increments, but I want a different angle increment of snapping when it comes to rays.

Ideally, these would just be separate values to config instead of being joined.

**Comment by cdverrett94** [comment]
That should be pretty be easy to accomplish. I'll separate them out.

**Comment by cdverrett94** [comment]
@zeltordaeon I just updated to include this, but its only in FVTT 0.8.x version of the module.
